# Generated by Django 2.2.4 on 2026-01-16 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceFingerprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='设备指纹')),
                ('phone', models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='关联手机号')),
                ('ai_trial_start', models.DateField(blank=True, null=True, verbose_name='AI试用开始时间')),
                ('ai_trial_end', models.DateField(blank=True, null=True, verbose_name='AI试用结束时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '设备指纹',
                'verbose_name_plural': '设备指纹',
                'db_table': 'device_fingerprints',
            },
        ),
        migrations.CreateModel(
            name='UsageStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='设备指纹')),
                ('phone', models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='手机号')),
                ('action_type', models.CharField(default='greeting', max_length=20, verbose_name='操作类型')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '使用统计',
                'verbose_name_plural': '使用统计',
                'db_table': 'usage_stats',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='手机号')),
                ('config', models.TextField(blank=True, null=True, verbose_name='用户配置 (JSON字符串)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'users',
            },
        ),
        migrations.AddIndex(
            model_name='usagestats',
            index=models.Index(fields=['fingerprint'], name='usage_stats_fingerp_97c2b6_idx'),
        ),
        migrations.AddIndex(
            model_name='usagestats',
            index=models.Index(fields=['phone'], name='usage_stats_phone_68920f_idx'),
        ),
        migrations.AddIndex(
            model_name='usagestats',
            index=models.Index(fields=['created_at'], name='usage_stats_created_31d9ea_idx'),
        ),
    ]
